# Generated by Django 4.2.1 on 2023-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_dosen_id_teacher_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='feature_image',
            field=models.ImageField(null=True, upload_to='course_imgs/'),
        ),
    ]
