# Generated by Django 4.2.1 on 2023-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_feature_image_course_feature_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='techs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
